### ISSUE TITLE
[BUG] "Cannot mount AppImage" notification when trying to do `sh path/to/file.sh`

### ISSUE THREAD

**Issue by Arbee4ever** [borisnliscool/deckboard-commands#3]
When I use this extension and set the command to `sh path/to/file.sh`, I keep getting this notification 
![image](https://github.com/borisnliscool/deckboard-commands/assets/45911516/3481fc61-3098-4bee-9cc5-cf18bb539c3f)
I'm on Fedora 40 and Version 3.0.0-rc9.1 of Deckboard
I also reported this here: https://github.com/rivafarabi/deckboard/issues/1063

**Comment by borisnliscool** [comment]
I'm not really actively maintaining this anymore, and I'm not using fedora myself so I'm not going to fix this I'm afraid.
